export const bodyTypesPayload = [
  "SUVs",
  "Convertibles",
  "Coupes",
  "Crossovers",
  "Hatchbacks",
  "Luxury Vehicles",
  "Minivans and Vans",
  "Pickup Trucks",
  "Sedans",
  "Sports Cars",
  "Wagons",
];

export const bodyTypesData = bodyTypesPayload.map((bodyType) => ({
  title: bodyType,
}));

export const makeBodyTypeData = [
  {
    slug: "acura",
    body_type_slugs: [
      "crossovers",
      "hatchbacks",
      "luxury-cars",
      "sedans",
      "sports-cars",
      "suvs",
      "wagons",
    ],
  },
  {
    slug: "audi",
    body_type_slugs: [
      "convertibles",
      "coupes",
      "crossovers",
      "hatchbacks",
      "luxury-cars",
      "sedans",
      "sports-cars",
      "suvs",
      "wagons",
    ],
  },
  {
    slug: "bmw",
    body_type_slugs: [
      "convertibles",
      "coupes",
      "crossovers",
      "hatchbacks",
      "luxury-cars",
      "sedans",
      "sports-cars",
      "suvs",
      "wagons",
    ],
  },
  {
    slug: "buick",
    body_type_slugs: [
      "convertibles",
      "coupes",
      "crossovers",
      "hatchbacks",
      "luxury-cars",
      "sedans",
      "suvs",
      "wagons",
    ],
  },
  {
    slug: "cadillac",
    body_type_slugs: [
      "coupes",
      "crossovers",
      "luxury-cars",
      "sedans",
      "sports-cars",
      "suvs",
    ],
  },

  {
    slug: "chevrolet",
    body_type_slugs: [
      "convertibles",
      "coupes",
      "crossovers",
      "hatchbacks",
      "minivans-and-vans",
      "pickup-trucks",
      "sedans",
      "sports-cars",
      "suvs",
      "wagons",
    ],
  },

  {
    slug: "chrysler",
    body_type_slugs: [
      "convertibles",
      "coupes",
      "luxury-cars",
      "minivans-and-vans",
      "sedans",
    ],
  },
  {
    slug: "dodge",
    body_type_slugs: [
      "coupes",
      "hatchbacks",
      "minivans-and-vans",
      "sedans",
      "sports-cars",
      "suvs",
      "wagons",
    ],
  },
];

export const bodyTypeMakeData = [
  {
    body_type_slug: "convertibles",
    make_slugs: [
      "audi",
      "bmw",
      "buick",
      "chevrolet",
      "chrysler",
      "fiat",
      "ford",
      "jaguar",
      "lexux",
      "mazda",
      "mercedes-benz",
      "mini",
      "mitsubishi",
      "nissan",
      "porsche",
      "smart",
      "volkswagen",
      "volvo",
    ],
  },
  {
    body_type_slug: "coupes",
    make_slugs: [
      "audi",
      "lexus",
      "mercedes-benz",
      "mini",
      "mitsubishi",
      "nissan",
      "porsche",
      "scion",
      "smart",
      "subaru",
      "toyota",
      "volkswagen",
      "volvo",
    ],
  },
  {
    body_type_slug: "crossovers",
    make_slugs: [
      "acura",
      "audi",
      "bmw",
      "buick",
      "cadillac",
      "chevrolet",
      "fiat",
      "ford",
      "gmc",
      "honda",
      "hyundai",
      "infiniti",
      "jaguar",
      "jeep",
      "kia",
      "lexus",
      "lincoln",
      "mazda",
      "mercedes-benz",
      "mitsubishi",
      "nissan",
      "porsche",
      "subaru",
      "toyota",
      "volkswagen",
      "volvo",
    ],
  },
  {
    body_type_slug: "hatchbacks",
    make_slugs: [
      "acura",
      "audi",
      "bmw",
      "buick",
      "chevrolet",
      "dodge",
      "fiat",
      "ford",
      "honda",
      "hyundai",
      "kia",
      "lexus",
      "mazda",
      "mercedes-benz",
      "mini",
      "mitsubishi",
      "nissan",
      "scion",
      "subaru",
      "tesla",
      "toyota",
      "volkswagen",
      "volvo",
    ],
  },
  {
    body_type_slug: "luxury-cars",
    make_slugs: [
      "acura",
      "audi",
      "bmw",
      "buick",
      "cadillac",
      "chrysler",
      "genesis",
      "hyundai",
      "infiniti",
      "jaguar",
      "kia",
      "land-rover",
      "lexus",
      "lincoln",
      "mercedes-benz",
      "mercury",
      "porche",
      "tesla",
      "volkswagen",
      "volvo",
    ],
  },
  {
    body_type_slug: "minivans-and-vans",
    make_slugs: [
      "acura",
      "audi",
      "bmw",
      "buick",
      "cadillac",
      "chrysler",
      "genesis",
      "hyundai",
      "infiniti",
      "jaguar",
      "kia",
      "land-rover",
      "lexus",
      "lincoln",
      "mercedes-benz",
      "mercury",
      "porche",
      "tesla",
      "volkswagen",
      "volvo",
    ],
  },
  {
    body_type_slug: "pickup-trucks",
    make_slugs: [
      "chevrolet",
      "ford",
      "gmc",
      "honda",
      "hyundai",
      "jeep",
      "mercedes-benz",
      "nissan",
      "ram",
      "toyota",
    ],
  },
  {
    body_type_slug: "sedans",
    make_slugs: [
      "acura",
      "audi",
      "bmw",
      "buick",
      "cadillac",
      "chevrolet",
      "chrysler",
      "dodge",
      "ford",
      "genesis",
      "honda",
      "hyundai",
      "infiniti",
      "jaguar",
      "kia",
      "lexus",
      "lincoln",
      "mazda",
      "mercedes-benz",
      "mercury",
      "mini",
      "mitsubishi",
      "nissan",
      "porsche",
      "scion",
      "subaru",
      "tesla",
      "toyota",
      "volkswagen",
      "volvo",
    ],
  },
  {
    body_type_slug: "sports-cars",
    make_slugs: [
      "acura",
      "audi",
      "bmw",
      "cadillac",
      "chevrolet",
      "dodge",
      "fiat",
      "ford",
      "genesis",
      "honda",
      "hyundai",
      "infiniti",
      "jaguar",
      "lexus",
      "mazda",
      "mercedes-benz",
      "mini",
      "mitsubishi",
      "nissan",
      "porsche",
      "scion",
      "smart",
      "toyota",
      "volkswagen",
    ],
  },
  {
    body_type_slug: "suvs",
    make_slugs: [
      "acura",
      "audi",
      "bmw",
      "buick",
      "cadillac",
      "chevrolet",
      "dodge",
      "fiat",
      "ford",
      "genesis",
      "gmc",
      "honda",
      "hyundai",
      "infiniti",
      "jaguar",
      "jeep",
      "kia",
      "land-rover",
      "lexus",
      "lincoln",
      "mazda",
      "mercedes-benz",
      "mini",
      "mitsubishi",
      "nissan",
      "porsche",
      "subaru",
      "tesla",
      "toyota",
      "volkswagen",
      "volvo",
    ],
  },
  {
    body_type_slug: "wagons",
    make_slugs: [
      "acura",
      "audi",
      "bmw",
      "buick",
      "cadillac",
      "chevrolet",
      "dodge",
      "fiat",
      "ford",
      "genesis",
      "gmc",
      "honda",
      "hyundai",
      "infiniti",
      "jaguar",
      "jeep",
      "kia",
      "land-rover",
      "lexus",
      "lincoln",
      "mazda",
      "mercedes-benz",
      "mini",
      "mitsubishi",
      "nissan",
      "porsche",
      "subaru",
      "tesla",
      "toyota",
      "volkswagen",
      "volvo",
    ],
  },
];
