const data = [
  {
    name: "!",
    displayName: "!",
    count: 24,
    urlSegment: "!",
    selected: false,
    removeSegments: [],
  },
  // {
  //   name: "+",
  //   displayName: "+",
  //   count: 111,
  //   urlSegment: "+",
  //   selected: false,
  //   removeSegments: [],
  // },
  {
    name: "10 Series",
    displayName: "10 Series",
    count: 1,
    urlSegment: "10-series",
    selected: false,
  },
  {
    name: "100D",
    displayName: "100D",
    count: 6,
    urlSegment: "100d",
    selected: false,
    removeSegments: [],
  },
  { name: "100th Anniversary", displayName: "100th Anniversary", count: 1 },
  {
    name: "110",
    displayName: "110",
    count: 2,
    urlSegment: "110",
    selected: false,
    removeSegments: [],
  },
  {
    name: "110 SE",
    displayName: "110 SE",
    count: 1,
    urlSegment: "110-se",
    selected: false,
  },
  {
    name: "110 X",
    displayName: "110 X",
    count: 1,
    urlSegment: "110-x",
    selected: false,
  },
  {
    name: "110 X-Dynamic SE",
    displayName: "110 X-Dynamic SE",
    count: 2,
    urlSegment: "110-x-dynamic-se",
  },
  {
    name: "1794",
    displayName: "1794",
    count: 5,
    urlSegment: "1794",
    selected: false,
    removeSegments: [],
  },
  {
    name: "1957 Edition",
    displayName: "1957 Edition",
    count: 1,
    urlSegment: "1957-edition",
  },
  {
    name: "1LT",
    displayName: "1LT",
    count: 4,
    urlSegment: "1lt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "1SS",
    displayName: "1SS",
    count: 2,
    urlSegment: "1ss",
    selected: false,
    removeSegments: [],
  },
  {
    name: "2.0",
    displayName: "2.0",
    count: 4,
    urlSegment: "2-0",
    selected: false,
    removeSegments: [],
  },
  {
    name: "2.0I",
    displayName: "2.0I",
    count: 5,
    urlSegment: "2-0i",
    selected: false,
    removeSegments: [],
  },
  {
    name: "2.0I Limited",
    displayName: "2.0I Limited",
    count: 18,
    urlSegment: "2-0i-limited",
  },
  {
    name: "2.0I Premium",
    displayName: "2.0I Premium",
    count: 45,
    urlSegment: "2-0i-premium",
  },
  { name: "2.0I Sport Limited", displayName: "2.0I Sport Limited", count: 9 },
  { name: "2.0I Sport Premium", displayName: "2.0I Sport Premium", count: 12 },
  {
    name: "2.0T",
    displayName: "2.0T",
    count: 14,
    urlSegment: "2-0t",
    selected: false,
    removeSegments: [],
  },
  {
    name: "2.0T Premium",
    displayName: "2.0T Premium",
    count: 3,
    urlSegment: "2-0t-premium",
  },
  {
    name: "2.0XT Touring",
    displayName: "2.0XT Touring",
    count: 8,
    urlSegment: "2-0xt--touring",
  },
  {
    name: "2.0XT Premium",
    displayName: "2.0XT Premium",
    count: 5,
    urlSegment: "2-0xt-premium",
  },
  {
    name: "2.5 S",
    displayName: "2.5 S",
    count: 1,
    urlSegment: "2-5-s",
    selected: false,
  },
  {
    name: "2.5 S Preferred Package",
    displayName: "2.5 S Preferred Package",
    count: 6,
  },
  {
    name: "2.5 S Premium Package",
    displayName: "2.5 S Premium Package",
    count: 4,
  },
  {
    name: "2.5 S Premium Plus Package",
    displayName: "2.5 S Premium Plus Package",
    count: 3,
  },
  {
    name: "2.5 S Select Package",
    displayName: "2.5 S Select Package",
    count: 2,
  },
  {
    name: "2.5 Turbo Premium Plus",
    displayName: "2.5 Turbo Premium Plus",
    count: 3,
  },
  {
    name: "2.5I",
    displayName: "2.5I",
    count: 62,
    urlSegment: "2-5i",
    selected: false,
    removeSegments: [],
  },
  {
    name: "2.5I Limited",
    displayName: "2.5I Limited",
    count: 121,
    urlSegment: "2-5i-limited",
  },
  {
    name: "2.5I Premium",
    displayName: "2.5I Premium",
    count: 191,
    urlSegment: "2-5i-premium",
  },
  {
    name: "2.5I Sport",
    displayName: "2.5I Sport",
    count: 9,
    urlSegment: "2-5i-sport",
    selected: false,
  },
  {
    name: "2.5I Touring",
    displayName: "2.5I Touring",
    count: 19,
    urlSegment: "2-5i-touring",
  },
  {
    name: "2.5X",
    displayName: "2.5X",
    count: 5,
    urlSegment: "2-5x",
    selected: false,
    removeSegments: [],
  },
  {
    name: "2.5X Limited",
    displayName: "2.5X Limited",
    count: 5,
    urlSegment: "2-5x-limited",
  },
  {
    name: "2.5X Premium",
    displayName: "2.5X Premium",
    count: 11,
    urlSegment: "2-5x-premium",
  },
  {
    name: "2.5X Touring",
    displayName: "2.5X Touring",
    count: 2,
    urlSegment: "2-5x-touring",
  },
  {
    name: "2.5XT Premium",
    displayName: "2.5XT Premium",
    count: 1,
    urlSegment: "2-5xt-premium",
  },
  {
    name: "2016.5 Grand Touring",
    displayName: "2016.5 Grand Touring",
    count: 2,
  },
  {
    name: "2016.5 Touring",
    displayName: "2016.5 Touring",
    count: 7,
    urlSegment: "2016-5-touring",
  },
  {
    name: "20D Prestige",
    displayName: "20D Prestige",
    count: 2,
    urlSegment: "20d-prestige",
  },
  {
    name: "25T",
    displayName: "25T",
    count: 5,
    urlSegment: "25t",
    selected: false,
    removeSegments: [],
  },
  {
    name: "25T Premium",
    displayName: "25T Premium",
    count: 23,
    urlSegment: "25t-premium",
  },
  {
    name: "25T Prestige",
    displayName: "25T Prestige",
    count: 3,
    urlSegment: "25t-prestige",
  },
  {
    name: "25T R-Sport",
    displayName: "25T R-Sport",
    count: 2,
    urlSegment: "25t-r-sport",
    selected: false,
  },
  {
    name: "296HP",
    displayName: "296HP",
    count: 2,
    urlSegment: "296hp",
    selected: false,
  },
  {
    name: "2LT",
    displayName: "2LT",
    count: 8,
    urlSegment: "2lt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "2SS",
    displayName: "2SS",
    count: 6,
    urlSegment: "2ss",
    selected: false,
    removeSegments: [],
  },
  {
    name: "3.0 Supercharged",
    displayName: "3.0 Supercharged",
    count: 1,
    urlSegment: "3-0-supercharged",
  },
  {
    name: "3.3T",
    displayName: "3.3T",
    count: 2,
    urlSegment: "3-3t",
    selected: false,
    removeSegments: [],
  },
  {
    name: "3.6R Limited",
    displayName: "3.6R Limited",
    count: 26,
    urlSegment: "3-6r-limited",
  },
  {
    name: "3.6R Touring",
    displayName: "3.6R Touring",
    count: 9,
    urlSegment: "3-6r-touring",
  },
  {
    name: "30T Portfolio",
    displayName: "30T Portfolio",
    count: 3,
    urlSegment: "30t-portfolio",
  },
  {
    name: "30T Premium",
    displayName: "30T Premium",
    count: 2,
    urlSegment: "30t-premium",
    selected: false,
  },
  {
    name: "30t Prestige",
    displayName: "30t Prestige",
    count: 7,
    urlSegment: "30t-prestige",
  },
  {
    name: "30t R-Sport",
    displayName: "30t R-Sport",
    count: 2,
    urlSegment: "30t-r-sport",
    selected: false,
  },
  {
    name: "340HP",
    displayName: "340HP",
    count: 1,
    urlSegment: "340hp",
    selected: false,
  },
  {
    name: "35t Portfolio",
    displayName: "35t Portfolio",
    count: 1,
    urlSegment: "35t-portfolio",
  },
  {
    name: "35th Anniversary",
    displayName: "35th Anniversary",
    count: 1,
    urlSegment: "35th-anniversary",
  },
  {
    name: "392 Hemi Scat Pack Shaker",
    displayName: "392 Hemi Scat Pack Shaker",
    count: 2,
  },
  {
    name: "3LT",
    displayName: "3LT",
    count: 3,
    urlSegment: "3lt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "4",
    displayName: "4",
    count: 4,
    urlSegment: "4",
    selected: false,
    removeSegments: [],
  },
  {
    name: "427",
    displayName: "427",
    count: 1,
    urlSegment: "427",
    selected: false,
    removeSegments: [],
  },
  {
    name: "4S",
    displayName: "4S",
    count: 1,
    urlSegment: "4s",
    selected: false,
    removeSegments: [],
  },
  {
    name: "4S Executive",
    displayName: "4S Executive",
    count: 1,
    urlSegment: "4s-executive",
  },
  {
    name: "50TH Anniversary Edition",
    displayName: "50TH Anniversary Edition",
    count: 2,
  },
  {
    name: "70TH Anniv",
    displayName: "70TH Anniv",
    count: 1,
    urlSegment: "70th-anniv",
    selected: false,
  },
  {
    name: "75TH Anniversary Edition",
    displayName: "75TH Anniversary Edition",
    count: 7,
  },
  {
    name: "80th Anniversary",
    displayName: "80th Anniversary",
    count: 13,
    urlSegment: "80th-anniversary",
  },
  { name: "860 Special Edition", displayName: "860 Special Edition", count: 1 },
  {
    name: "90 X-Dynamic S",
    displayName: "90 X-Dynamic S",
    count: 1,
    urlSegment: "90-x-dynamic-s",
  },
  {
    name: "Abarth",
    displayName: "Abarth",
    count: 13,
    urlSegment: "abarth",
    selected: false,
  },
  {
    name: "Activ",
    displayName: "Activ",
    count: 12,
    urlSegment: "activ",
    selected: false,
  },
  {
    name: "Advance",
    displayName: "Advance",
    count: 20,
    urlSegment: "advance",
    selected: false,
  },
  {
    name: "Advanced",
    displayName: "Advanced",
    count: 5,
    urlSegment: "advanced",
    selected: false,
  },
  {
    name: "Adventure",
    displayName: "Adventure",
    count: 9,
    urlSegment: "adventure",
    selected: false,
  },
  {
    name: "ALL4",
    displayName: "ALL4",
    count: 21,
    urlSegment: "all4",
    selected: false,
    removeSegments: [],
  },
  {
    name: "All-New Latitude",
    displayName: "All-New Latitude",
    count: 7,
    urlSegment: "all-new-latitude",
  },
  {
    name: "All-New Limited",
    displayName: "All-New Limited",
    count: 4,
    urlSegment: "all-new-limited",
  },
  {
    name: "All-New Sport",
    displayName: "All-New Sport",
    count: 6,
    urlSegment: "all-new-sport",
  },
  { name: "All-New Trailhawk", displayName: "All-New Trailhawk", count: 4 },
  {
    name: "All-New Unlimited Rubicon",
    displayName: "All-New Unlimited Rubicon",
    count: 4,
  },
  {
    name: "All-New Unlimited Sahara",
    displayName: "All-New Unlimited Sahara",
    count: 11,
  },
  {
    name: "All-New Unlimited Sport",
    displayName: "All-New Unlimited Sport",
    count: 12,
  },
  {
    name: "All-New Unlimited Sport S",
    displayName: "All-New Unlimited Sport S",
    count: 4,
  },
  {
    name: "Altitude",
    displayName: "Altitude",
    count: 135,
    urlSegment: "altitude",
    selected: false,
  },
  {
    name: "American Value",
    displayName: "American Value",
    count: 2,
    urlSegment: "american-value",
  },
  { name: "Anniversary Edition", displayName: "Anniversary Edition", count: 1 },
  {
    name: "A-Spec",
    displayName: "A-Spec",
    count: 23,
    urlSegment: "a-spec",
    selected: false,
  },
  { name: "Autobiography LWB", displayName: "Autobiography LWB", count: 1 },
  {
    name: "Autograph",
    displayName: "Autograph",
    count: 1,
    urlSegment: "autograph",
    selected: false,
  },
  {
    name: "Avenir",
    displayName: "Avenir",
    count: 12,
    urlSegment: "avenir",
    selected: false,
  },
  {
    name: "AWD",
    displayName: "AWD",
    count: 35,
    urlSegment: "awd",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Badlands",
    displayName: "Badlands",
    count: 7,
    urlSegment: "badlands",
    selected: false,
  },
  {
    name: "BE",
    displayName: "BE",
    count: 1,
    urlSegment: "be",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Big Bend",
    displayName: "Big Bend",
    count: 38,
    urlSegment: "big-bend",
    selected: false,
  },
  {
    name: "Bighorn",
    displayName: "Bighorn",
    count: 111,
    urlSegment: "bighorn",
    selected: false,
  },
  {
    name: "Black Diamond",
    displayName: "Black Diamond",
    count: 4,
    urlSegment: "black-diamond",
  },
  {
    name: "Black Edition",
    displayName: "Black Edition",
    count: 18,
    urlSegment: "black-edition",
  },
  {
    name: "Black Label",
    displayName: "Black Label",
    count: 7,
    urlSegment: "black-label",
    selected: false,
  },
  {
    name: "Blue",
    displayName: "Blue",
    count: 26,
    urlSegment: "trim-blue",
    selected: false,
  },
  {
    name: "Bullitt",
    displayName: "Bullitt",
    count: 3,
    urlSegment: "bullitt",
    selected: false,
  },
  {
    name: "C",
    displayName: "C",
    count: 13,
    urlSegment: "c",
    selected: false,
    removeSegments: [],
  },
  { name: "California Route 1", displayName: "California Route 1", count: 2 },
  {
    name: "Calligraphy",
    displayName: "Calligraphy",
    count: 17,
    urlSegment: "calligraphy",
  },
  {
    name: "Carbon Edition",
    displayName: "Carbon Edition",
    count: 11,
    urlSegment: "carbon-edition",
  },
  {
    name: "Carbon Edition Turbo",
    displayName: "Carbon Edition Turbo",
    count: 5,
  },
  {
    name: "Carrera",
    displayName: "Carrera",
    count: 1,
    urlSegment: "carrera",
    selected: false,
  },
  {
    name: "Carrera S",
    displayName: "Carrera S",
    count: 1,
    urlSegment: "carrera-s",
    selected: false,
  },
  {
    name: "Checkered Flag",
    displayName: "Checkered Flag",
    count: 3,
    urlSegment: "checkered-flag",
  },
  {
    name: "Chronos",
    displayName: "Chronos",
    count: 1,
    urlSegment: "chronos",
    selected: false,
  },
  {
    name: "Citadel",
    displayName: "Citadel",
    count: 3,
    urlSegment: "citadel",
    selected: false,
  },
  {
    name: "Classica",
    displayName: "Classica",
    count: 2,
    urlSegment: "classica",
    selected: false,
  },
  {
    name: "Club",
    displayName: "Club",
    count: 4,
    urlSegment: "club",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Clubman",
    displayName: "Clubman",
    count: 3,
    urlSegment: "clubman",
    selected: false,
  },
  {
    name: "Clubman S",
    displayName: "Clubman S",
    count: 1,
    urlSegment: "clubman-s",
    selected: false,
  },
  {
    name: "Competition",
    displayName: "Competition",
    count: 1,
    urlSegment: "competition",
    selected: false,
  },
  {
    name: "Convenience",
    displayName: "Convenience",
    count: 20,
    urlSegment: "convenience",
  },
  {
    name: "Countryman",
    displayName: "Countryman",
    count: 1,
    urlSegment: "countryman",
    selected: false,
  },
  {
    name: "Countryman S",
    displayName: "Countryman S",
    count: 6,
    urlSegment: "countryman-s",
  },
  {
    name: "Coupe",
    displayName: "Coupe",
    count: 1,
    urlSegment: "coupe",
    selected: false,
  },
  {
    name: "Crafted Line",
    displayName: "Crafted Line",
    count: 2,
    urlSegment: "crafted-line",
  },
  {
    name: "Crew",
    displayName: "Crew",
    count: 2,
    urlSegment: "crew",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Crossroad",
    displayName: "Crossroad",
    count: 24,
    urlSegment: "crossroad",
    selected: false,
  },
  {
    name: "Crossroad Plus",
    displayName: "Crossroad Plus",
    count: 6,
    urlSegment: "crossroad-plus",
  },
  {
    name: "Custom",
    displayName: "Custom",
    count: 59,
    urlSegment: "custom",
    selected: false,
  },
  { name: "Custom Trail Boss", displayName: "Custom Trail Boss", count: 3 },
  {
    name: "CX",
    displayName: "CX",
    count: 3,
    urlSegment: "cx",
    selected: false,
    removeSegments: [],
  },
  {
    name: "CXL",
    displayName: "CXL",
    count: 4,
    urlSegment: "cxl",
    selected: false,
    removeSegments: [],
  },
  {
    name: "CXS",
    displayName: "CXS",
    count: 1,
    urlSegment: "cxs",
    selected: false,
    removeSegments: [],
  },
  {
    name: "D",
    displayName: "D",
    count: 3,
    urlSegment: "d",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Daytona",
    displayName: "Daytona",
    count: 2,
    urlSegment: "daytona",
    selected: false,
  },
  {
    name: "Daytona 392",
    displayName: "Daytona 392",
    count: 1,
    urlSegment: "daytona-392",
    selected: false,
  },
  {
    name: "DE",
    displayName: "DE",
    count: 3,
    urlSegment: "de",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Deka World Range Extender",
    displayName: "Deka World Range Extender",
    count: 2,
  },
  {
    name: "Denim",
    displayName: "Denim",
    count: 1,
    urlSegment: "denim",
    selected: false,
  },
  {
    name: "Desert Runner",
    displayName: "Desert Runner",
    count: 5,
    urlSegment: "desert-runner",
  },
  {
    name: "DesertHawk",
    displayName: "DesertHawk",
    count: 1,
    urlSegment: "deserthawk",
    selected: false,
  },
  {
    name: "Design",
    displayName: "Design",
    count: 1,
    urlSegment: "design",
    selected: false,
  },
  {
    name: "DIESEL",
    displayName: "DIESEL",
    count: 2,
    urlSegment: "diesel",
    selected: false,
  },
  {
    name: "DX",
    displayName: "DX",
    count: 2,
    urlSegment: "dx",
    selected: false,
    removeSegments: [],
  },
  {
    name: "DXI",
    displayName: "DXI",
    count: 2,
    urlSegment: "dxi",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Dynamic",
    displayName: "Dynamic",
    count: 3,
    urlSegment: "dynamic",
    selected: false,
  },
  {
    name: "E iPerformance",
    displayName: "E iPerformance",
    count: 7,
    urlSegment: "e-iperformance",
  },
  {
    name: "Easy",
    displayName: "Easy",
    count: 7,
    urlSegment: "easy",
    selected: false,
    removeSegments: [],
  },
  {
    name: "ECO",
    displayName: "ECO",
    count: 26,
    urlSegment: "eco",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Ecoboost",
    displayName: "Ecoboost",
    count: 59,
    urlSegment: "ecoboost",
    selected: false,
  },
  {
    name: "Ecoboost Premium",
    displayName: "Ecoboost Premium",
    count: 35,
    urlSegment: "ecoboost-premium",
  },
  {
    name: "Edition",
    displayName: "Edition",
    count: 1,
    urlSegment: "edition",
    selected: false,
  },
  {
    name: "Edition One",
    displayName: "Edition One",
    count: 1,
    urlSegment: "edition-one",
    selected: false,
  },
  {
    name: "ELITE",
    displayName: "ELITE",
    count: 22,
    urlSegment: "elite",
    selected: false,
  },
  {
    name: "ES",
    displayName: "ES",
    count: 159,
    urlSegment: "trim-es",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Essence",
    displayName: "Essence",
    count: 86,
    urlSegment: "essence",
    selected: false,
  },
  {
    name: "Essential",
    displayName: "Essential",
    count: 18,
    urlSegment: "essential",
    selected: false,
  },
  {
    name: "ESV",
    displayName: "ESV",
    count: 2,
    urlSegment: "esv",
    selected: false,
    removeSegments: [],
  },
  {
    name: "ESV Luxury",
    displayName: "ESV Luxury",
    count: 1,
    urlSegment: "esv-luxury",
    selected: false,
  },
  {
    name: "EX",
    displayName: "EX",
    count: 808,
    urlSegment: "ex",
    selected: false,
    removeSegments: [],
  },
  {
    name: "EX Premium",
    displayName: "EX Premium",
    count: 11,
    urlSegment: "ex-premium",
    selected: false,
  },
  {
    name: "EX Sport",
    displayName: "EX Sport",
    count: 1,
    urlSegment: "ex-sport",
    selected: false,
  },
  {
    name: "EX-L",
    displayName: "EX-L",
    count: 531,
    urlSegment: "ex-l",
    selected: false,
  },
  {
    name: "Express",
    displayName: "Express",
    count: 44,
    urlSegment: "express",
    selected: false,
  },
  {
    name: "EX-T",
    displayName: "EX-T",
    count: 36,
    urlSegment: "ex-t",
    selected: false,
    removeSegments: [],
  },
  {
    name: "FE",
    displayName: "FE",
    count: 23,
    urlSegment: "fe",
    selected: false,
    removeSegments: [],
  },
  {
    name: "First Edition",
    displayName: "First Edition",
    count: 17,
    urlSegment: "first-edition",
  },
  {
    name: "Five",
    displayName: "Five",
    count: 6,
    urlSegment: "five",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Four",
    displayName: "Four",
    count: 19,
    urlSegment: "four",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Four Touring",
    displayName: "Four Touring",
    count: 3,
    urlSegment: "four-touring",
  },
  {
    name: "Freedom",
    displayName: "Freedom",
    count: 1,
    urlSegment: "freedom",
    selected: false,
  },
  {
    name: "F-Sport",
    displayName: "F-Sport",
    count: 112,
    urlSegment: "f-sport",
    selected: false,
  },
  {
    name: "F-SPORT Handling",
    displayName: "F-SPORT Handling",
    count: 1,
    urlSegment: "f-sport-handling",
  },
  {
    name: "Giga World",
    displayName: "Giga World",
    count: 2,
    urlSegment: "giga-world",
    selected: false,
  },
  {
    name: "Giga World Range Extender",
    displayName: "Giga World Range Extender",
    count: 1,
  },
  {
    name: "GL",
    displayName: "GL",
    count: 3,
    urlSegment: "gl",
    selected: false,
    removeSegments: [],
  },
  {
    name: "GLS",
    displayName: "GLS",
    count: 186,
    urlSegment: "gls",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Grand Select",
    displayName: "Grand Select",
    count: 5,
    urlSegment: "grand-select",
  },
  {
    name: "Grand Sport",
    displayName: "Grand Sport",
    count: 2,
    urlSegment: "grand-sport",
    selected: false,
  },
  {
    name: "Grand Touring",
    displayName: "Grand Touring",
    count: 173,
    urlSegment: "grand-touring",
  },
  {
    name: "Grand Touring Reserve",
    displayName: "Grand Touring Reserve",
    count: 13,
  },
  {
    name: "GS",
    displayName: "GS",
    count: 17,
    urlSegment: "trim-gs",
    selected: false,
    removeSegments: [],
  },
  {
    name: "GS Sport",
    displayName: "GS Sport",
    count: 2,
    urlSegment: "gs-sport",
    selected: false,
  },
  {
    name: "GT",
    displayName: "GT",
    count: 180,
    urlSegment: "gt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "GT Plus",
    displayName: "GT Plus",
    count: 5,
    urlSegment: "gt-plus",
    selected: false,
  },
  {
    name: "GT Premium",
    displayName: "GT Premium",
    count: 15,
    urlSegment: "gt-premium",
    selected: false,
  },
  {
    name: "GT Sport",
    displayName: "GT Sport",
    count: 3,
    urlSegment: "gt-sport",
    selected: false,
  },
  {
    name: "GT1",
    displayName: "GT1",
    count: 4,
    urlSegment: "gt1",
    selected: false,
    removeSegments: [],
  },
  {
    name: "GT2",
    displayName: "GT2",
    count: 2,
    urlSegment: "gt2",
    selected: false,
    removeSegments: [],
  },
  {
    name: "GT-Line",
    displayName: "GT-Line",
    count: 86,
    urlSegment: "gt-line",
    selected: false,
  },
  {
    name: "GT-Line Turbo",
    displayName: "GT-Line Turbo",
    count: 3,
    urlSegment: "gt-line-turbo",
  },
  {
    name: "GTS",
    displayName: "GTS",
    count: 5,
    urlSegment: "gts",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Hakone Edition",
    displayName: "Hakone Edition",
    count: 1,
    urlSegment: "hakone-edition",
  },
  {
    name: "Heritage",
    displayName: "Heritage",
    count: 1,
    urlSegment: "heritage",
    selected: false,
  },
  {
    name: "High Altitude",
    displayName: "High Altitude",
    count: 36,
    urlSegment: "high-altitude",
  },
  {
    name: "High Country",
    displayName: "High Country",
    count: 16,
    urlSegment: "high-country",
  },
  {
    name: "HSE",
    displayName: "HSE",
    count: 86,
    urlSegment: "hse",
    selected: false,
    removeSegments: [],
  },
  {
    name: "HSE Diesel",
    displayName: "HSE Diesel",
    count: 7,
    urlSegment: "hse-diesel",
    selected: false,
  },
  {
    name: "HSE DYNAMIC",
    displayName: "HSE DYNAMIC",
    count: 5,
    urlSegment: "hse-dynamic",
    selected: false,
  },
  {
    name: "HSE Luxury",
    displayName: "HSE Luxury",
    count: 4,
    urlSegment: "hse-luxury",
    selected: false,
  },
  { name: "HSE Silver Edition", displayName: "HSE Silver Edition", count: 5 },
  {
    name: "HST",
    displayName: "HST",
    count: 2,
    urlSegment: "hst",
    selected: false,
    removeSegments: [],
  },
  {
    name: "I",
    displayName: "I",
    count: 279,
    urlSegment: "i",
    selected: false,
    removeSegments: [],
  },
  {
    name: "I Gran Coupe",
    displayName: "I Gran Coupe",
    count: 16,
    urlSegment: "i-gran-coupe",
  },
  {
    name: "I Gran Turismo",
    displayName: "I Gran Turismo",
    count: 1,
    urlSegment: "i-gran-turismo",
  },
  {
    name: "I Grand Touring",
    displayName: "I Grand Touring",
    count: 29,
    urlSegment: "i-grand-touring",
  },
  {
    name: "I Sport",
    displayName: "I Sport",
    count: 49,
    urlSegment: "i-sport",
    selected: false,
  },
  {
    name: "I SV",
    displayName: "I SV",
    count: 2,
    urlSegment: "i-sv",
    selected: false,
    removeSegments: [],
  },
  {
    name: "I Touring",
    displayName: "I Touring",
    count: 61,
    urlSegment: "i-touring",
    selected: false,
  },
  {
    name: "I xDrive",
    displayName: "I xDrive",
    count: 47,
    urlSegment: "i-xdrive",
    selected: false,
  },
  {
    name: "I xDrive Gran Coupe",
    displayName: "I xDrive Gran Coupe",
    count: 15,
  },
  {
    name: "iPerformance",
    displayName: "iPerformance",
    count: 28,
    urlSegment: "iperformance",
  },
  {
    name: "Jeepster",
    displayName: "Jeepster",
    count: 9,
    urlSegment: "jeepster",
    selected: false,
  },
  {
    name: "Jet",
    displayName: "Jet",
    count: 2,
    urlSegment: "jet",
    selected: false,
    removeSegments: [],
  },
  { name: "John Cooper Works", displayName: "John Cooper Works", count: 8 },
  {
    name: "John Cooper Works ALL4",
    displayName: "John Cooper Works ALL4",
    count: 6,
  },
  {
    name: "John Cooper Works GP",
    displayName: "John Cooper Works GP",
    count: 1,
  },
  {
    name: "Journey",
    displayName: "Journey",
    count: 17,
    urlSegment: "journey",
    selected: false,
  },
  {
    name: "L",
    displayName: "L",
    count: 112,
    urlSegment: "l",
    selected: false,
    removeSegments: [],
  },
  {
    name: "L ECO",
    displayName: "L ECO",
    count: 1,
    urlSegment: "l-eco",
    selected: false,
  },
  {
    name: "L Luxe",
    displayName: "L Luxe",
    count: 1,
    urlSegment: "l-luxe",
    selected: false,
  },
  {
    name: "L Luxury",
    displayName: "L Luxury",
    count: 6,
    urlSegment: "l-luxury",
    selected: false,
  },
  {
    name: "L Portfolio",
    displayName: "L Portfolio",
    count: 3,
    urlSegment: "l-portfolio",
    selected: false,
  },
  {
    name: "L Supercharged",
    displayName: "L Supercharged",
    count: 1,
    urlSegment: "l-supercharged",
  },
  {
    name: "Landmark",
    displayName: "Landmark",
    count: 2,
    urlSegment: "landmark",
    selected: false,
  },
  {
    name: "Laramie",
    displayName: "Laramie",
    count: 69,
    urlSegment: "laramie",
    selected: false,
  },
  {
    name: "Laramie Limited",
    displayName: "Laramie Limited",
    count: 1,
    urlSegment: "laramie-limited",
  },
  {
    name: "Laramie Longhorn",
    displayName: "Laramie Longhorn",
    count: 11,
    urlSegment: "laramie-longhorn",
  },
  {
    name: "LAREDO",
    displayName: "LAREDO",
    count: 69,
    urlSegment: "laredo",
    selected: false,
  },
  {
    name: "Laredo E",
    displayName: "Laredo E",
    count: 40,
    urlSegment: "laredo-e",
    selected: false,
  },
  {
    name: "Laredo X",
    displayName: "Laredo X",
    count: 12,
    urlSegment: "laredo-x",
    selected: false,
  },
  {
    name: "Lariat",
    displayName: "Lariat",
    count: 4,
    urlSegment: "lariat",
    selected: false,
  },
  {
    name: "Latitude",
    displayName: "Latitude",
    count: 291,
    urlSegment: "latitude",
    selected: false,
  },
  {
    name: "Latitude Lux",
    displayName: "Latitude Lux",
    count: 5,
    urlSegment: "latitude-lux",
  },
  {
    name: "Latitude Plus",
    displayName: "Latitude Plus",
    count: 60,
    urlSegment: "latitude-plus",
  },
  {
    name: "LAUNCH EDITION",
    displayName: "LAUNCH EDITION",
    count: 4,
    urlSegment: "launch-edition",
  },
  {
    name: "LE",
    displayName: "LE",
    count: 793,
    urlSegment: "le",
    selected: false,
    removeSegments: [],
  },
  {
    name: "LE Eco",
    displayName: "LE Eco",
    count: 8,
    urlSegment: "le-eco",
    selected: false,
  },
  {
    name: "LE Eco Plus",
    displayName: "LE Eco Plus",
    count: 1,
    urlSegment: "le-eco-plus",
    selected: false,
  },
  {
    name: "LE Plus",
    displayName: "LE Plus",
    count: 11,
    urlSegment: "le-plus",
    selected: false,
  },
  {
    name: "LE Premium",
    displayName: "LE Premium",
    count: 1,
    urlSegment: "le-premium",
    selected: false,
  },
  {
    name: "Leather",
    displayName: "Leather",
    count: 31,
    urlSegment: "leather",
    selected: false,
  },
  {
    name: "Li xDrive",
    displayName: "Li xDrive",
    count: 1,
    urlSegment: "li-xdrive",
    selected: false,
  },
  {
    name: "Light",
    displayName: "Light",
    count: 1,
    urlSegment: "light",
    selected: false,
  },
  {
    name: "Limited",
    displayName: "Limited",
    count: 1243,
    urlSegment: "limited",
    selected: false,
  },
  { name: "Limited Night Shade", displayName: "Limited Night Shade", count: 1 },
  {
    name: "Limited Platinum",
    displayName: "Limited Platinum",
    count: 28,
    urlSegment: "limited-platinum",
  },
  {
    name: "Limited Premium",
    displayName: "Limited Premium",
    count: 2,
    urlSegment: "limited-premium",
  },
  {
    name: "Limited Ultimate",
    displayName: "Limited Ultimate",
    count: 5,
    urlSegment: "limited-ultimate",
  },
  {
    name: "Limited X",
    displayName: "Limited X",
    count: 22,
    urlSegment: "limited-x",
    selected: false,
  },
  {
    name: "Limited XT",
    displayName: "Limited XT",
    count: 5,
    urlSegment: "limited-xt",
    selected: false,
  },
  {
    name: "Lonestar",
    displayName: "Lonestar",
    count: 17,
    urlSegment: "lonestar",
    selected: false,
  },
  {
    name: "Long Range",
    displayName: "Long Range",
    count: 28,
    urlSegment: "long-range",
    selected: false,
  },
  {
    name: "Long Range Plus",
    displayName: "Long Range Plus",
    count: 8,
    urlSegment: "long-range-plus",
  },
  {
    name: "Longhorn",
    displayName: "Longhorn",
    count: 8,
    urlSegment: "longhorn",
    selected: false,
  },
  {
    name: "Lounge",
    displayName: "Lounge",
    count: 19,
    urlSegment: "lounge",
    selected: false,
  },
  {
    name: "LS",
    displayName: "LS",
    count: 548,
    urlSegment: "trim-ls",
    selected: false,
    removeSegments: [],
  },
  {
    name: "LT",
    displayName: "LT",
    count: 1192,
    urlSegment: "lt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "LT Cloth",
    displayName: "LT Cloth",
    count: 7,
    urlSegment: "lt-cloth",
    selected: false,
  },
  {
    name: "LT Leather",
    displayName: "LT Leather",
    count: 5,
    urlSegment: "lt-leather",
    selected: false,
  },
  {
    name: "LT Trail Boss",
    displayName: "LT Trail Boss",
    count: 7,
    urlSegment: "lt-trail-boss",
  },
  {
    name: "LT Z71",
    displayName: "LT Z71",
    count: 16,
    urlSegment: "lt-z71",
    selected: false,
  },
  {
    name: "LT1",
    displayName: "LT1",
    count: 4,
    urlSegment: "lt1",
    selected: false,
    removeSegments: [],
  },
  {
    name: "LTZ",
    displayName: "LTZ",
    count: 97,
    urlSegment: "ltz",
    selected: false,
    removeSegments: [],
  },
  { name: "LTZ Black Diamond", displayName: "LTZ Black Diamond", count: 1 },
  {
    name: "LTZ Z71",
    displayName: "LTZ Z71",
    count: 5,
    urlSegment: "ltz-z71",
    selected: false,
  },
  {
    name: "Lusso",
    displayName: "Lusso",
    count: 5,
    urlSegment: "lusso",
    selected: false,
  },
  {
    name: "LUX",
    displayName: "LUX",
    count: 1,
    urlSegment: "lux",
    selected: false,
    removeSegments: [],
  },
  {
    name: "LUXE",
    displayName: "LUXE",
    count: 149,
    urlSegment: "luxe",
    selected: false,
  },
  {
    name: "LUXURY",
    displayName: "LUXURY",
    count: 136,
    urlSegment: "luxury",
    selected: false,
  },
  {
    name: "LX",
    displayName: "LX",
    count: 1464,
    urlSegment: "trim-lx",
    selected: false,
  },
  {
    name: "LXI",
    displayName: "LXI",
    count: 11,
    urlSegment: "lxi",
    selected: false,
    removeSegments: [],
  },
  {
    name: "LX-P",
    displayName: "LX-P",
    count: 15,
    urlSegment: "lx-p",
    selected: false,
    removeSegments: [],
  },
  {
    name: "LXS",
    displayName: "LXS",
    count: 191,
    urlSegment: "lxs",
    selected: false,
    removeSegments: [],
  },
  {
    name: "LX-S",
    displayName: "LX-S",
    count: 9,
    urlSegment: "lx-s",
    selected: false,
    removeSegments: [],
  },
  { name: "LXS Special Edition", displayName: "LXS Special Edition", count: 1 },
  {
    name: "M",
    displayName: "M",
    count: 3,
    urlSegment: "m",
    selected: false,
    removeSegments: [],
  },
  {
    name: "M35i",
    displayName: "M35i",
    count: 1,
    urlSegment: "m35i",
    selected: false,
    removeSegments: [],
  },
  {
    name: "M40I",
    displayName: "M40I",
    count: 12,
    urlSegment: "m40i",
    selected: false,
    removeSegments: [],
  },
  {
    name: "M50i",
    displayName: "M50i",
    count: 1,
    urlSegment: "m50i",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Mach 1",
    displayName: "Mach 1",
    count: 5,
    urlSegment: "mach-1",
    selected: false,
  },
  {
    name: "Mainstreet",
    displayName: "Mainstreet",
    count: 3,
    urlSegment: "mainstreet",
    selected: false,
  },
  {
    name: "Mazdaspeed",
    displayName: "Mazdaspeed",
    count: 2,
    urlSegment: "mazdaspeed",
    selected: false,
  },
  {
    name: "Mega World",
    displayName: "Mega World",
    count: 3,
    urlSegment: "mega-world",
    selected: false,
  },
  {
    name: "Mid Range",
    displayName: "Mid Range",
    count: 2,
    urlSegment: "mid-range",
    selected: false,
  },
  {
    name: "Mojave",
    displayName: "Mojave",
    count: 9,
    urlSegment: "mojave",
    selected: false,
  },
  {
    name: "MONOGRAM",
    displayName: "MONOGRAM",
    count: 2,
    urlSegment: "monogram",
    selected: false,
  },
  {
    name: "N",
    displayName: "N",
    count: 4,
    urlSegment: "n",
    selected: false,
    removeSegments: [],
  },
  {
    name: "N Line",
    displayName: "N Line",
    count: 27,
    urlSegment: "n-line",
    selected: false,
  },
  {
    name: "Night",
    displayName: "Night",
    count: 5,
    urlSegment: "night",
    selected: false,
  },
  {
    name: "Nightfall",
    displayName: "Nightfall",
    count: 2,
    urlSegment: "nightfall",
    selected: false,
  },
  {
    name: "Nightshade",
    displayName: "Nightshade",
    count: 2,
    urlSegment: "nightshade",
    selected: false,
  },
  {
    name: "Nismo",
    displayName: "Nismo",
    count: 7,
    urlSegment: "nismo",
    selected: false,
  },
  {
    name: "Nismo RS",
    displayName: "Nismo RS",
    count: 2,
    urlSegment: "nismo-rs",
    selected: false,
  },
  {
    name: "One",
    displayName: "One",
    count: 9,
    urlSegment: "one",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Onyx Edition",
    displayName: "Onyx Edition",
    count: 1,
    urlSegment: "onyx-edition",
  },
  {
    name: "Onyx Edition XT",
    displayName: "Onyx Edition XT",
    count: 11,
    urlSegment: "onyx-edition-xt",
  },
  {
    name: "Outback",
    displayName: "Outback",
    count: 1,
    urlSegment: "trim-outback",
    selected: false,
  },
  {
    name: "Outdoorsman",
    displayName: "Outdoorsman",
    count: 1,
    urlSegment: "outdoorsman",
    selected: false,
  },
  {
    name: "Outer Banks",
    displayName: "Outer Banks",
    count: 21,
    urlSegment: "outer-banks",
  },
  {
    name: "Overland",
    displayName: "Overland",
    count: 65,
    urlSegment: "overland",
    selected: false,
  },
  {
    name: "Oxford Edition",
    displayName: "Oxford Edition",
    count: 4,
    urlSegment: "oxford-edition",
  },
  {
    name: "P100D",
    displayName: "P100D",
    count: 3,
    urlSegment: "p100d",
    selected: false,
  },
  {
    name: "P300",
    displayName: "P300",
    count: 1,
    urlSegment: "p300",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Paceman",
    displayName: "Paceman",
    count: 2,
    urlSegment: "paceman",
    selected: false,
  },
  {
    name: "Paceman S",
    displayName: "Paceman S",
    count: 1,
    urlSegment: "paceman-s",
    selected: false,
  },
  {
    name: "Passion",
    displayName: "Passion",
    count: 13,
    urlSegment: "passion",
    selected: false,
  },
  {
    name: "Performance",
    displayName: "Performance",
    count: 21,
    urlSegment: "performance",
  },
  {
    name: "Persona Series",
    displayName: "Persona Series",
    count: 3,
    urlSegment: "persona-series",
  },
  {
    name: "Pinnacle",
    displayName: "Pinnacle",
    count: 1,
    urlSegment: "pinnacle",
    selected: false,
  },
  {
    name: "Plaid",
    displayName: "Plaid",
    count: 4,
    urlSegment: "plaid",
    selected: false,
  },
  {
    name: "Platinum",
    displayName: "Platinum",
    count: 168,
    urlSegment: "platinum",
    selected: false,
  },
  {
    name: "Platinum Reserve",
    displayName: "Platinum Reserve",
    count: 3,
    urlSegment: "platinum-reserve",
  },
  {
    name: "PLUS",
    displayName: "PLUS",
    count: 10,
    urlSegment: "plus",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Pop",
    displayName: "Pop",
    count: 53,
    urlSegment: "pop",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Power Wagon",
    displayName: "Power Wagon",
    count: 4,
    urlSegment: "power-wagon",
    selected: false,
  },
  {
    name: "Preferred",
    displayName: "Preferred",
    count: 185,
    urlSegment: "preferred",
    selected: false,
  },
  {
    name: "Preferred II",
    displayName: "Preferred II",
    count: 3,
    urlSegment: "preferred-ii",
  },
  {
    name: "Premier",
    displayName: "Premier",
    count: 125,
    urlSegment: "premier",
    selected: false,
  },
  {
    name: "Premiere",
    displayName: "Premiere",
    count: 6,
    urlSegment: "premiere",
    selected: false,
  },
  {
    name: "Premium",
    displayName: "Premium",
    count: 706,
    urlSegment: "premium",
    selected: false,
  },
  {
    name: "Premium 2",
    displayName: "Premium 2",
    count: 3,
    urlSegment: "premium-2",
    selected: false,
  },
  {
    name: "Premium A-Spec",
    displayName: "Premium A-Spec",
    count: 7,
    urlSegment: "premium-a-spec",
  },
  {
    name: "Premium Luxury",
    displayName: "Premium Luxury",
    count: 66,
    urlSegment: "premium-luxury",
  },
  {
    name: "Premium Plus",
    displayName: "Premium Plus",
    count: 367,
    urlSegment: "premium-plus",
  },
  { name: "Premium Plus S-Line", displayName: "Premium Plus S-Line", count: 8 },
  { name: "Premium Plus Sport", displayName: "Premium Plus Sport", count: 4 },
  { name: "Premium Series.Gray", displayName: "Premium Series.Gray", count: 1 },
  {
    name: "Premium S-Line",
    displayName: "Premium S-Line",
    count: 8,
    urlSegment: "premium-s-line",
  },
  {
    name: "Premium Sport",
    displayName: "Premium Sport",
    count: 1,
    urlSegment: "premium-sport",
  },
  {
    name: "Prerunner",
    displayName: "Prerunner",
    count: 14,
    urlSegment: "prerunner",
    selected: false,
  },
  {
    name: "Prestige",
    displayName: "Prestige",
    count: 96,
    urlSegment: "prestige",
    selected: false,
  },
  {
    name: "Prestige S-Line",
    displayName: "Prestige S-Line",
    count: 5,
    urlSegment: "prestige-s-line",
  },
  {
    name: "Prime",
    displayName: "Prime",
    count: 1,
    urlSegment: "prime",
    selected: false,
  },
  {
    name: "PRO-4X",
    displayName: "PRO-4X",
    count: 20,
    urlSegment: "pro-4x",
    selected: false,
  },
  {
    name: "PRO-X",
    displayName: "PRO-X",
    count: 1,
    urlSegment: "pro-x",
    selected: false,
  },
  {
    name: "Pure",
    displayName: "Pure",
    count: 32,
    urlSegment: "pure",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Pure Plus",
    displayName: "Pure Plus",
    count: 3,
    urlSegment: "pure-plus",
    selected: false,
  },
  {
    name: "Pure Premium",
    displayName: "Pure Premium",
    count: 1,
    urlSegment: "pure-premium",
  },
  {
    name: "R",
    displayName: "R",
    count: 1,
    urlSegment: "r",
    selected: false,
    removeSegments: [],
  },
  {
    name: "R/T",
    displayName: "R/T",
    count: 63,
    urlSegment: "rt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "R/T Max",
    displayName: "R/T Max",
    count: 1,
    urlSegment: "rt-max",
    selected: false,
  },
  {
    name: "R/T Plus",
    displayName: "R/T Plus",
    count: 5,
    urlSegment: "rt-plus",
    selected: false,
  },
  {
    name: "R/T Scat Pack",
    displayName: "R/T Scat Pack",
    count: 22,
    urlSegment: "rt-scat-pack",
  },
  { name: "R/T Scat Pack Plus", displayName: "R/T Scat Pack Plus", count: 3 },
  {
    name: "R/T Scat Pack Widebody",
    displayName: "R/T Scat Pack Widebody",
    count: 2,
  },
  {
    name: "R/T Shaker",
    displayName: "R/T Shaker",
    count: 1,
    urlSegment: "rt-shaker",
    selected: false,
  },
  {
    name: "Rallye",
    displayName: "Rallye",
    count: 4,
    urlSegment: "rallye",
    selected: false,
  },
  {
    name: "Range Extender",
    displayName: "Range Extender",
    count: 1,
    urlSegment: "range-extender",
  },
  {
    name: "R-Dynamic HSE",
    displayName: "R-Dynamic HSE",
    count: 4,
    urlSegment: "r-dynamic-hse",
  },
  {
    name: "R-Dynamic S",
    displayName: "R-Dynamic S",
    count: 13,
    urlSegment: "r-dynamic-s",
  },
  {
    name: "R-Dynamic SE",
    displayName: "R-Dynamic SE",
    count: 25,
    urlSegment: "r-dynamic-se",
  },
  {
    name: "Rebel",
    displayName: "Rebel",
    count: 27,
    urlSegment: "rebel",
    selected: false,
  },
  {
    name: "Red Edition",
    displayName: "Red Edition",
    count: 1,
    urlSegment: "red-edition",
    selected: false,
  },
  {
    name: "Red Sport 400",
    displayName: "Red Sport 400",
    count: 9,
    urlSegment: "red-sport-400",
  },
  {
    name: "Reserve",
    displayName: "Reserve",
    count: 124,
    urlSegment: "reserve",
    selected: false,
  },
  {
    name: "Reserve II",
    displayName: "Reserve II",
    count: 4,
    urlSegment: "reserve-ii",
    selected: false,
  },
  {
    name: "RF",
    displayName: "RF",
    count: 1,
    urlSegment: "rf",
    selected: false,
    removeSegments: [],
  },
  {
    name: "RF Club",
    displayName: "RF Club",
    count: 12,
    urlSegment: "rf-club",
    selected: false,
  },
  {
    name: "RF Grand Touring",
    displayName: "RF Grand Touring",
    count: 8,
    urlSegment: "rf-grand-touring",
  },
  {
    name: "RS",
    displayName: "RS",
    count: 41,
    urlSegment: "rs",
    selected: false,
    removeSegments: [],
  },
  {
    name: "R-Spec",
    displayName: "R-Spec",
    count: 1,
    urlSegment: "r-spec",
    selected: false,
  },
  {
    name: "R-Sport",
    displayName: "R-Sport",
    count: 12,
    urlSegment: "r-sport",
    selected: false,
  },
  {
    name: "RST",
    displayName: "RST",
    count: 19,
    urlSegment: "rst",
    selected: false,
    removeSegments: [],
  },
  {
    name: "RTL",
    displayName: "RTL",
    count: 12,
    urlSegment: "rtl",
    selected: false,
    removeSegments: [],
  },
  {
    name: "RTL-E",
    displayName: "RTL-E",
    count: 10,
    urlSegment: "rtl-e",
    selected: false,
  },
  {
    name: "RTL-T",
    displayName: "RTL-T",
    count: 3,
    urlSegment: "rtl-t",
    selected: false,
  },
  {
    name: "RTS",
    displayName: "RTS",
    count: 1,
    urlSegment: "rts",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Rubicon",
    displayName: "Rubicon",
    count: 15,
    urlSegment: "rubicon",
    selected: false,
  },
  {
    name: "S",
    displayName: "S",
    count: 1536,
    urlSegment: "s",
    selected: false,
    removeSegments: [],
  },
  {
    name: "S ALL4",
    displayName: "S ALL4",
    count: 43,
    urlSegment: "s-all4",
    selected: false,
  },
  {
    name: "S All4 Signature",
    displayName: "S All4 Signature",
    count: 3,
    urlSegment: "s-all4-signature",
  },
  {
    name: "S Alloy Edition",
    displayName: "S Alloy Edition",
    count: 2,
    urlSegment: "s-alloy-edition",
  },
  {
    name: "S E ALL4",
    displayName: "S E ALL4",
    count: 3,
    urlSegment: "s-e-all4",
    selected: false,
  },
  {
    name: "S Grand Touring",
    displayName: "S Grand Touring",
    count: 3,
    urlSegment: "s-grand-touring",
  },
  {
    name: "S Iconic",
    displayName: "S Iconic",
    count: 2,
    urlSegment: "s-iconic",
    selected: false,
  },
  {
    name: "S Plus",
    displayName: "S Plus",
    count: 81,
    urlSegment: "s-plus",
    selected: false,
  },
  {
    name: "S Range Extender",
    displayName: "S Range Extender",
    count: 1,
    urlSegment: "s-range-extender",
  },
  {
    name: "S Signature",
    displayName: "S Signature",
    count: 1,
    urlSegment: "s-signature",
    selected: false,
  },
  {
    name: "S Touring",
    displayName: "S Touring",
    count: 4,
    urlSegment: "s-touring",
    selected: false,
  },
  {
    name: "Sahara",
    displayName: "Sahara",
    count: 5,
    urlSegment: "sahara",
    selected: false,
  },
  {
    name: "Scat Pack",
    displayName: "Scat Pack",
    count: 7,
    urlSegment: "scat-pack",
    selected: false,
  },
  { name: "Scat Pack Widebody", displayName: "Scat Pack Widebody", count: 2 },
  {
    name: "SDrive28i",
    displayName: "SDrive28i",
    count: 75,
    urlSegment: "sdrive28i",
    selected: false,
  },
  {
    name: "sDrive30i",
    displayName: "sDrive30i",
    count: 40,
    urlSegment: "sdrive30i",
    selected: false,
  },
  {
    name: "SDrive35i",
    displayName: "SDrive35i",
    count: 12,
    urlSegment: "sdrive35i",
    selected: false,
  },
  {
    name: "sDrive40i",
    displayName: "sDrive40i",
    count: 6,
    urlSegment: "sdrive40i",
    selected: false,
  },
  {
    name: "SE",
    displayName: "SE",
    count: 1836,
    urlSegment: "se",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SE Apex",
    displayName: "SE Apex",
    count: 2,
    urlSegment: "se-apex",
    selected: false,
  },
  {
    name: "SE Diesel",
    displayName: "SE Diesel",
    count: 5,
    urlSegment: "se-diesel",
    selected: false,
  },
  {
    name: "SE Energi",
    displayName: "SE Energi",
    count: 3,
    urlSegment: "se-energi",
    selected: false,
  },
  {
    name: "SE Hybrid",
    displayName: "SE Hybrid",
    count: 5,
    urlSegment: "se-hybrid",
    selected: false,
  },
  {
    name: "SE Night Shade",
    displayName: "SE Night Shade",
    count: 15,
    urlSegment: "se-night-shade",
  },
  {
    name: "SE Plus",
    displayName: "SE Plus",
    count: 5,
    urlSegment: "se-plus",
    selected: false,
  },
  {
    name: "SE Premium",
    displayName: "SE Premium",
    count: 12,
    urlSegment: "se-premium",
    selected: false,
  },
  {
    name: "SE Premium Plus",
    displayName: "SE Premium Plus",
    count: 7,
    urlSegment: "se-premium-plus",
  },
  {
    name: "SE SPORT",
    displayName: "SE SPORT",
    count: 7,
    urlSegment: "se-sport",
    selected: false,
  },
  {
    name: "SE Ultimate",
    displayName: "SE Ultimate",
    count: 4,
    urlSegment: "se-ultimate",
    selected: false,
  },
  {
    name: "SEL",
    displayName: "SEL",
    count: 700,
    urlSegment: "sel",
    selected: false,
    removeSegments: [],
  },
  { name: "SEL Black Edition", displayName: "SEL Black Edition", count: 1 },
  {
    name: "SEL Convenience",
    displayName: "SEL Convenience",
    count: 1,
    urlSegment: "sel-convenience",
  },
  { name: "SEL Launch Edition", displayName: "SEL Launch Edition", count: 1 },
  {
    name: "SEL Plus",
    displayName: "SEL Plus",
    count: 39,
    urlSegment: "sel-plus",
    selected: false,
  },
  {
    name: "SEL Premium",
    displayName: "SEL Premium",
    count: 2,
    urlSegment: "sel-premium",
    selected: false,
  },
  {
    name: "SELECT",
    displayName: "SELECT",
    count: 87,
    urlSegment: "select",
    selected: false,
  },
  {
    name: "Sensory",
    displayName: "Sensory",
    count: 14,
    urlSegment: "sensory",
    selected: false,
  },
  {
    name: "SE-R Spec V",
    displayName: "SE-R Spec V",
    count: 1,
    urlSegment: "se-r-spec-v",
    selected: false,
  },
  {
    name: "Series III",
    displayName: "Series III",
    count: 1,
    urlSegment: "series-iii",
    selected: false,
  },
  {
    name: "SES",
    displayName: "SES",
    count: 10,
    urlSegment: "ses",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SH-AWD",
    displayName: "SH-AWD",
    count: 34,
    urlSegment: "sh-awd",
    selected: false,
  },
  {
    name: "SH-AWD Advance",
    displayName: "SH-AWD Advance",
    count: 5,
    urlSegment: "sh-awd-advance",
  },
  {
    name: "SH-AWD A-Spec",
    displayName: "SH-AWD A-Spec",
    count: 20,
    urlSegment: "sh-awd-a-spec",
  },
  { name: "SH-AWD Technology", displayName: "SH-AWD Technology", count: 3 },
  {
    name: "SH-AWD Type S Advance",
    displayName: "SH-AWD Type S Advance",
    count: 1,
  },
  {
    name: "Shelby GT350",
    displayName: "Shelby GT350",
    count: 5,
    urlSegment: "shelby-gt350",
  },
  {
    name: "Shelby GT500",
    displayName: "Shelby GT500",
    count: 2,
    urlSegment: "shelby-gt500",
  },
  {
    name: "SHO",
    displayName: "SHO",
    count: 11,
    urlSegment: "sho",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SI",
    displayName: "SI",
    count: 45,
    urlSegment: "si",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Signature",
    displayName: "Signature",
    count: 26,
    urlSegment: "signature",
    selected: false,
  },
  { name: "Signature Edition", displayName: "Signature Edition", count: 2 },
  { name: "Signature Limited", displayName: "Signature Limited", count: 1 },
  {
    name: "SL",
    displayName: "SL",
    count: 395,
    urlSegment: "sl",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SL PLUS",
    displayName: "SL PLUS",
    count: 3,
    urlSegment: "sl-plus",
    selected: false,
  },
  {
    name: "S-Line Premium",
    displayName: "S-Line Premium",
    count: 10,
    urlSegment: "s-line-premium",
  },
  {
    name: "S-Line Premium Plus",
    displayName: "S-Line Premium Plus",
    count: 13,
  },
  {
    name: "S-Line Prestige",
    displayName: "S-Line Prestige",
    count: 2,
    urlSegment: "s-line-prestige",
  },
  {
    name: "SLT",
    displayName: "SLT",
    count: 19,
    urlSegment: "slt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SP",
    displayName: "SP",
    count: 4,
    urlSegment: "sp",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Special Edition",
    displayName: "Special Edition",
    count: 18,
    urlSegment: "special-edition",
  },
  {
    name: "Sport",
    displayName: "Sport",
    count: 1048,
    urlSegment: "sport",
    selected: false,
  },
  {
    name: "Sport Edition",
    displayName: "Sport Edition",
    count: 4,
    urlSegment: "sport-edition",
  },
  {
    name: "Sport S",
    displayName: "Sport S",
    count: 17,
    urlSegment: "sport-s",
    selected: false,
  },
  {
    name: "Sport SE",
    displayName: "Sport SE",
    count: 17,
    urlSegment: "sport-se",
    selected: false,
  },
  {
    name: "Sport Touring",
    displayName: "Sport Touring",
    count: 57,
    urlSegment: "sport-touring",
  },
  {
    name: "SR",
    displayName: "SR",
    count: 284,
    urlSegment: "sr",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SR Turbo",
    displayName: "SR Turbo",
    count: 1,
    urlSegment: "sr-turbo",
    selected: false,
  },
  {
    name: "SR5",
    displayName: "SR5",
    count: 107,
    urlSegment: "sr5",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SR5 Premium",
    displayName: "SR5 Premium",
    count: 25,
    urlSegment: "sr5-premium",
  },
  {
    name: "SRT",
    displayName: "SRT",
    count: 1,
    urlSegment: "srt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SRT 392",
    displayName: "SRT 392",
    count: 3,
    urlSegment: "srt-392",
    selected: false,
  },
  {
    name: "SS",
    displayName: "SS",
    count: 15,
    urlSegment: "trim-ss",
    selected: false,
    removeSegments: [],
  },
  {
    name: "ST",
    displayName: "ST",
    count: 7,
    urlSegment: "st",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Standard",
    displayName: "Standard",
    count: 31,
    urlSegment: "standard",
    selected: false,
  },
  {
    name: "Standard Range",
    displayName: "Standard Range",
    count: 7,
    urlSegment: "standard-range",
  },
  {
    name: "Standard Range Plus",
    displayName: "Standard Range Plus",
    count: 13,
  },
  {
    name: "Sterling Edition",
    displayName: "Sterling Edition",
    count: 3,
    urlSegment: "sterling-edition",
  },
  {
    name: "STI",
    displayName: "STI",
    count: 10,
    urlSegment: "sti",
    selected: false,
    removeSegments: [],
  },
  {
    name: "STI Limited",
    displayName: "STI Limited",
    count: 8,
    urlSegment: "sti-limited",
    selected: false,
  },
  {
    name: "Stingray",
    displayName: "Stingray",
    count: 9,
    urlSegment: "stingray",
    selected: false,
  },
  {
    name: "Stingray Z51",
    displayName: "Stingray Z51",
    count: 6,
    urlSegment: "stingray--z51",
  },
  {
    name: "Stingray 2LT",
    displayName: "Stingray 2LT",
    count: 1,
    urlSegment: "stingray-2lt",
  },
  {
    name: "Summit",
    displayName: "Summit",
    count: 24,
    urlSegment: "summit",
    selected: false,
  },
  {
    name: "Summit Reserve",
    displayName: "Summit Reserve",
    count: 1,
    urlSegment: "summit-reserve",
  },
  {
    name: "Supercharged",
    displayName: "Supercharged",
    count: 14,
    urlSegment: "supercharged",
  },
  {
    name: "Supercharged Dynamic",
    displayName: "Supercharged Dynamic",
    count: 3,
  },
  {
    name: "Supercharged LWB",
    displayName: "Supercharged LWB",
    count: 3,
    urlSegment: "supercharged-lwb",
  },
  {
    name: "SV",
    displayName: "SV",
    count: 1034,
    urlSegment: "sv",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SV Plus",
    displayName: "SV Plus",
    count: 2,
    urlSegment: "sv-plus",
    selected: false,
  },
  {
    name: "SVR",
    displayName: "SVR",
    count: 2,
    urlSegment: "svr",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SX",
    displayName: "SX",
    count: 110,
    urlSegment: "sx",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SX Prestige",
    displayName: "SX Prestige",
    count: 12,
    urlSegment: "sx-prestige",
  },
  { name: "SX Prestige X-Line", displayName: "SX Prestige X-Line", count: 1 },
  {
    name: "SX Touring",
    displayName: "SX Touring",
    count: 1,
    urlSegment: "sx-touring",
    selected: false,
  },
  {
    name: "SXL",
    displayName: "SXL",
    count: 12,
    urlSegment: "sxl",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SXT",
    displayName: "SXT",
    count: 183,
    urlSegment: "sxt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "SXT Plus",
    displayName: "SXT Plus",
    count: 27,
    urlSegment: "sxt-plus",
    selected: false,
  },
  {
    name: "SXT Sport Rallye",
    displayName: "SXT Sport Rallye",
    count: 1,
    urlSegment: "sxt-sport-rallye",
  },
  {
    name: "Technology",
    displayName: "Technology",
    count: 4,
    urlSegment: "technology",
    selected: false,
  },
  { name: "Technology A-Spec", displayName: "Technology A-Spec", count: 4 },
  {
    name: "Tera World",
    displayName: "Tera World",
    count: 10,
    urlSegment: "tera-world",
    selected: false,
  },
  {
    name: "Tera World Range Extender",
    displayName: "Tera World Range Extender",
    count: 1,
  },
  {
    name: "Three",
    displayName: "Three",
    count: 36,
    urlSegment: "three",
    selected: false,
  },
  {
    name: "Three Touring",
    displayName: "Three Touring",
    count: 5,
    urlSegment: "three-touring",
  },
  {
    name: "Titanium",
    displayName: "Titanium",
    count: 142,
    urlSegment: "titanium",
    selected: false,
  },
  {
    name: "Titanium Hybrid",
    displayName: "Titanium Hybrid",
    count: 2,
    urlSegment: "titanium-hybrid",
  },
  {
    name: "Titanium Premium",
    displayName: "Titanium Premium",
    count: 6,
    urlSegment: "titanium-premium",
  },
  {
    name: "Titanium Premium Plus",
    displayName: "Titanium Premium Plus",
    count: 1,
  },
  { name: "Titanium Prestige", displayName: "Titanium Prestige", count: 1 },
  {
    name: "Touring",
    displayName: "Touring",
    count: 535,
    urlSegment: "touring",
    selected: false,
  },
  {
    name: "Touring Elite",
    displayName: "Touring Elite",
    count: 8,
    urlSegment: "touring-elite",
  },
  {
    name: "Touring GLS",
    displayName: "Touring GLS",
    count: 5,
    urlSegment: "touring-gls",
    selected: false,
  },
  {
    name: "Touring L",
    displayName: "Touring L",
    count: 77,
    urlSegment: "touring-l",
    selected: false,
  },
  {
    name: "Touring L Plus",
    displayName: "Touring L Plus",
    count: 7,
    urlSegment: "touring-l-plus",
  },
  // {
  //   name: "Touring L-Plus",
  //   displayName: "Touring L-Plus",
  //   count: 3,
  //   urlSegment: "touring-l-plus",
  // },
  {
    name: "TOURING PLUS",
    displayName: "TOURING PLUS",
    count: 8,
    urlSegment: "touring-plus",
  },
  {
    name: "Touring SE",
    displayName: "Touring SE",
    count: 4,
    urlSegment: "touring-se",
    selected: false,
  },
  {
    name: "Touring XT",
    displayName: "Touring XT",
    count: 7,
    urlSegment: "touring-xt",
    selected: false,
  },
  {
    name: "Tradesman",
    displayName: "Tradesman",
    count: 57,
    urlSegment: "tradesman",
    selected: false,
  },
  {
    name: "Tradesman SLT",
    displayName: "Tradesman SLT",
    count: 1,
    urlSegment: "tradesman-slt",
  },
  {
    name: "Trail Premium",
    displayName: "Trail Premium",
    count: 1,
    urlSegment: "trail-premium",
  },
  {
    name: "Trail Special Edition",
    displayName: "Trail Special Edition",
    count: 2,
  },
  {
    name: "Trailhawk",
    displayName: "Trailhawk",
    count: 130,
    urlSegment: "trailhawk",
    selected: false,
  },
  {
    name: "Trailhawk Elite",
    displayName: "Trailhawk Elite",
    count: 1,
    urlSegment: "trailhawk-elite",
  },
  {
    name: "Trailhawk L Plus",
    displayName: "Trailhawk L Plus",
    count: 1,
    urlSegment: "trailhawk-l-plus",
  },
  {
    name: "Trailsport",
    displayName: "Trailsport",
    count: 3,
    urlSegment: "trailsport",
    selected: false,
  },
  {
    name: "TRD",
    displayName: "TRD",
    count: 7,
    urlSegment: "trd",
    selected: false,
    removeSegments: [],
  },
  {
    name: "TRD Off Road",
    displayName: "TRD Off Road",
    count: 52,
    urlSegment: "trd-off-road",
  },
  {
    name: "TRD Off Road Premium",
    displayName: "TRD Off Road Premium",
    count: 21,
  },
  {
    name: "TRD Pro",
    displayName: "TRD Pro",
    count: 16,
    urlSegment: "trd-pro",
    selected: false,
  },
  {
    name: "TRD SE",
    displayName: "TRD SE",
    count: 3,
    urlSegment: "trd-se",
    selected: false,
  },
  {
    name: "TRD Sport",
    displayName: "TRD Sport",
    count: 38,
    urlSegment: "trd-sport",
    selected: false,
  },
  {
    name: "Trekking",
    displayName: "Trekking",
    count: 14,
    urlSegment: "trekking",
    selected: false,
  },
  {
    name: "Trekking Plus",
    displayName: "Trekking Plus",
    count: 1,
    urlSegment: "trekking-plus",
  },
  {
    name: "TS",
    displayName: "TS",
    count: 1,
    urlSegment: "ts",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Turbo",
    displayName: "Turbo",
    count: 23,
    urlSegment: "turbo",
    selected: false,
  },
  {
    name: "Turbo Premium",
    displayName: "Turbo Premium",
    count: 1,
    urlSegment: "turbo-premium",
  },
  {
    name: "Two",
    displayName: "Two",
    count: 69,
    urlSegment: "two",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Two Eco",
    displayName: "Two Eco",
    count: 4,
    urlSegment: "two-eco",
    selected: false,
  },
  {
    name: "Type R",
    displayName: "Type R",
    count: 2,
    urlSegment: "type-r",
    selected: false,
  },
  {
    name: "Type-R Touring",
    displayName: "Type-R Touring",
    count: 13,
    urlSegment: "type-r-touring",
  },
  {
    name: "Ultimate",
    displayName: "Ultimate",
    count: 33,
    urlSegment: "ultimate",
    selected: false,
  },
  {
    name: "Ultra Luxury",
    displayName: "Ultra Luxury",
    count: 1,
    urlSegment: "ultra-luxury",
  },
  { name: "Unlimited Freedom", displayName: "Unlimited Freedom", count: 2 },
  { name: "Unlimited Rubicon", displayName: "Unlimited Rubicon", count: 24 },
  {
    name: "Unlimited Rubicon Recon",
    displayName: "Unlimited Rubicon Recon",
    count: 2,
  },
  {
    name: "Unlimited Sahara",
    displayName: "Unlimited Sahara",
    count: 58,
    urlSegment: "unlimited-sahara",
  },
  {
    name: "Unlimited Sahara Altitude",
    displayName: "Unlimited Sahara Altitude",
    count: 1,
  },
  {
    name: "Unlimited Sahara High Altitude",
    displayName: "Unlimited Sahara High Altitude",
    count: 3,
  },
  {
    name: "Unlimited Sport",
    displayName: "Unlimited Sport",
    count: 78,
    urlSegment: "unlimited-sport",
  },
  {
    name: "Unlimited Sport Altitude",
    displayName: "Unlimited Sport Altitude",
    count: 9,
  },
  { name: "Unlimited Sport S", displayName: "Unlimited Sport S", count: 26 },
  {
    name: "Unlimited Willys",
    displayName: "Unlimited Willys",
    count: 8,
    urlSegment: "unlimited-willys",
  },
  {
    name: "Unlimited Willys Sport",
    displayName: "Unlimited Willys Sport",
    count: 5,
  },
  {
    name: "Upland",
    displayName: "Upland",
    count: 6,
    urlSegment: "upland",
    selected: false,
  },
  {
    name: "Urbana Edition",
    displayName: "Urbana Edition",
    count: 1,
    urlSegment: "urbana-edition",
  },
  {
    name: "V",
    displayName: "V",
    count: 1,
    urlSegment: "v",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Value",
    displayName: "Value",
    count: 38,
    urlSegment: "value",
    selected: false,
  },
  {
    name: "Value Edition",
    displayName: "Value Edition",
    count: 62,
    urlSegment: "value-edition",
  },
  {
    name: "Venture",
    displayName: "Venture",
    count: 2,
    urlSegment: "venture",
    selected: false,
  },
  {
    name: "Warlock",
    displayName: "Warlock",
    count: 10,
    urlSegment: "warlock",
    selected: false,
  },
  {
    name: "Wave",
    displayName: "Wave",
    count: 1,
    urlSegment: "wave",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Wilderness",
    displayName: "Wilderness",
    count: 27,
    urlSegment: "wilderness",
    selected: false,
  },
  {
    name: "Wildtrak",
    displayName: "Wildtrak",
    count: 4,
    urlSegment: "wildtrak",
    selected: false,
  },
  {
    name: "Willy's",
    displayName: "Willy's",
    count: 3,
    urlSegment: "willys",
    selected: false,
  },
  {
    name: "Willys Sport",
    displayName: "Willys Sport",
    count: 1,
    urlSegment: "willys-sport",
  },
  {
    name: "Wind",
    displayName: "Wind",
    count: 13,
    urlSegment: "wind",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Work Truck",
    displayName: "Work Truck",
    count: 54,
    urlSegment: "work-truck",
    selected: false,
  },
  {
    name: "WRX",
    displayName: "WRX",
    count: 6,
    urlSegment: "trim-wrx",
    selected: false,
  },
  {
    name: "WRX Limited",
    displayName: "WRX Limited",
    count: 1,
    urlSegment: "wrx-limited",
    selected: false,
  },
  {
    name: "WRX Premium",
    displayName: "WRX Premium",
    count: 1,
    urlSegment: "wrx-premium",
    selected: false,
  },
  {
    name: "WRX STI",
    displayName: "WRX STI",
    count: 4,
    urlSegment: "wrx-sti",
    selected: false,
  },
  {
    name: "X",
    displayName: "X",
    count: 15,
    urlSegment: "x",
    selected: false,
    removeSegments: [],
  },
  { name: "xDrive iPerformance", displayName: "xDrive iPerformance", count: 3 },
  {
    name: "XDrive28i",
    displayName: "XDrive28i",
    count: 127,
    urlSegment: "trim-xdrive28i",
  },
  {
    name: "xDrive30e",
    displayName: "xDrive30e",
    count: 2,
    urlSegment: "xdrive30e",
    selected: false,
  },
  {
    name: "XDrive30i",
    displayName: "XDrive30i",
    count: 98,
    urlSegment: "xdrive30i",
    selected: false,
  },
  {
    name: "XDrive35D",
    displayName: "XDrive35D",
    count: 3,
    urlSegment: "xdrive35d",
    selected: false,
  },
  {
    name: "XDrive35i",
    displayName: "XDrive35i",
    count: 38,
    urlSegment: "xdrive35i",
    selected: false,
  },
  { name: "XDrive35i Premium", displayName: "XDrive35i Premium", count: 2 },
  {
    name: "XDrive40e",
    displayName: "XDrive40e",
    count: 12,
    urlSegment: "xdrive40e",
    selected: false,
  },
  {
    name: "xDrive40i",
    displayName: "xDrive40i",
    count: 36,
    urlSegment: "trim-xdrive40i",
    selected: false,
  },
  {
    name: "XDrive45e",
    displayName: "XDrive45e",
    count: 1,
    urlSegment: "xdrive45e",
    selected: false,
  },
  {
    name: "XDrive50i",
    displayName: "XDrive50i",
    count: 12,
    urlSegment: "xdrive50i",
    selected: false,
  },
  {
    name: "XI",
    displayName: "XI",
    count: 96,
    urlSegment: "xi",
    selected: false,
    removeSegments: [],
  },
  {
    name: "XI Gran Coupe",
    displayName: "XI Gran Coupe",
    count: 3,
    urlSegment: "xi-gran-coupe",
  },
  {
    name: "XI Gran Turismo",
    displayName: "XI Gran Turismo",
    count: 13,
    urlSegment: "xi-gran-turismo",
  },
  {
    name: "XL",
    displayName: "XL",
    count: 21,
    urlSegment: "xl",
    selected: false,
    removeSegments: [],
  },
  {
    name: "XLE",
    displayName: "XLE",
    count: 423,
    urlSegment: "xle",
    selected: false,
    removeSegments: [],
  },
  {
    name: "XLE Bronze",
    displayName: "XLE Bronze",
    count: 2,
    urlSegment: "xle-bronze",
    selected: false,
  },
  {
    name: "XLE Plus",
    displayName: "XLE Plus",
    count: 1,
    urlSegment: "xle-plus",
    selected: false,
  },
  {
    name: "XLE Premium",
    displayName: "XLE Premium",
    count: 41,
    urlSegment: "xle-premium",
  },
  {
    name: "XLE Touring",
    displayName: "XLE Touring",
    count: 4,
    urlSegment: "xle-touring",
    selected: false,
  },
  {
    name: "X-Line",
    displayName: "X-Line",
    count: 8,
    urlSegment: "x-line",
    selected: false,
  },
  {
    name: "X-Line EX",
    displayName: "X-Line EX",
    count: 2,
    urlSegment: "x-line-ex",
    selected: false,
  },
  {
    name: "X-Line S",
    displayName: "X-Line S",
    count: 1,
    urlSegment: "x-line-s",
    selected: false,
  },
  { name: "X-Line SX Prestige", displayName: "X-Line SX Prestige", count: 1 },
  {
    name: "XLS",
    displayName: "XLS",
    count: 2,
    urlSegment: "xls",
    selected: false,
    removeSegments: [],
  },
  {
    name: "XLT",
    displayName: "XLT",
    count: 35,
    urlSegment: "xlt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "XRT",
    displayName: "XRT",
    count: 4,
    urlSegment: "xrt",
    selected: false,
    removeSegments: [],
  },
  {
    name: "XSE",
    displayName: "XSE",
    count: 142,
    urlSegment: "xse",
    selected: false,
    removeSegments: [],
  },
  {
    name: "Z71",
    displayName: "Z71",
    count: 19,
    urlSegment: "z71",
    selected: false,
    removeSegments: [],
  },
  {
    name: "ZL1",
    displayName: "ZL1",
    count: 1,
    urlSegment: "zl1",
    selected: false,
    removeSegments: [],
  },
  {
    name: "ZR2",
    displayName: "ZR2",
    count: 9,
    urlSegment: "zr2",
    selected: false,
    removeSegments: [],
  },
];

const trimsData = data.map((item) => {
  return {
    title: item.displayName,
  };
});

export default trimsData;
